import {
  UserProfile,
  Department,
  AcademicClass,
  Course,
  AttendanceSession,
  AttendanceScanRecord,
  Assignment,
  Submission,
  Exam,
  GradeRecord,
  LeaveRequest,
  AIInsight,
  SystemNotification,
  StudentMasterRecord,
} from '../types';

export const INITIAL_STUDENT_MASTER: StudentMasterRecord[] = [
  {
    id: 'sm-001',
    registrationNumber: 'NEGU2023CS042',
    officialName: 'Aarav Sharma',
    officialEmail: 'aarav.sharma@negu.edu',
    departmentCode: 'CSE',
    classCode: 'CSE-3A',
    batchYear: 2023,
    status: 'ACTIVE',
  },
  {
    id: 'sm-002',
    registrationNumber: 'NEGU2023CS019',
    officialName: 'Priya Iyer',
    officialEmail: 'priya.iyer@negu.edu',
    departmentCode: 'CSE',
    classCode: 'CSE-3A',
    batchYear: 2023,
    status: 'ACTIVE',
  },
  {
    id: 'sm-003',
    registrationNumber: 'NEGU2023CS088',
    officialName: 'Rohan Verma',
    officialEmail: 'rohan.verma@negu.edu',
    departmentCode: 'CSE',
    classCode: 'CSE-3A',
    batchYear: 2023,
    status: 'ACTIVE',
  },
  {
    id: 'sm-004',
    registrationNumber: 'NEGU2023CS055',
    officialName: 'Ananya Reddy',
    officialEmail: 'ananya.reddy@negu.edu',
    departmentCode: 'CSE',
    classCode: 'CSE-3A',
    batchYear: 2023,
    status: 'ACTIVE',
  },
  {
    id: 'sm-005',
    registrationNumber: 'NEGU2023CS071',
    officialName: 'Karthik Menon',
    officialEmail: 'karthik.menon@negu.edu',
    departmentCode: 'CSE',
    classCode: 'CSE-3A',
    batchYear: 2023,
    status: 'ACTIVE',
  },
];

export const INITIAL_USERS: Record<string, UserProfile> = {
  student: {
    id: 'user-std-01',
    email: 'aarav.sharma@negu.edu',
    fullName: 'Aarav Sharma',
    role: 'student',
    registrationNumber: 'NEGU2023CS042',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    departmentName: 'Computer Science & Engineering',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    isVerified: true,
    batchYear: 2023,
    semester: 6,
    currentGpa: 3.82,
    phone: '+91 98765 43210',
  },
  teacher: {
    id: 'user-tch-01',
    email: 'ramesh.kulkarni@negu.edu',
    fullName: 'Dr. Ramesh Kulkarni',
    role: 'teacher',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    departmentName: 'Computer Science & Engineering',
    isVerified: true,
    phone: '+91 94480 12345',
  },
  hod: {
    id: 'user-hod-01',
    email: 'sneha.deshmukh@negu.edu',
    fullName: 'Prof. Sneha Deshmukh',
    role: 'hod',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    departmentName: 'Computer Science & Engineering',
    isVerified: true,
    phone: '+91 98200 54321',
  },
  admin: {
    id: 'user-adm-01',
    email: 'admin.narayan@negu.edu',
    fullName: 'Dean S. K. Narayan',
    role: 'admin',
    departmentName: 'Institutional Administration',
    isVerified: true,
    phone: '+91 80 2345 6789',
  },
};

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-cse',
    code: 'CSE',
    name: 'Computer Science & Engineering',
    description: 'Autonomous systems, distributed databases, cloud architecture, and artificial intelligence.',
    hodId: 'user-hod-01',
    hodName: 'Prof. Sneha Deshmukh',
    studentCount: 480,
    facultyCount: 28,
    coursesCount: 34,
    avgAttendance: 85.6,
  },
  {
    id: 'dept-aids',
    code: 'AI&DS',
    name: 'Artificial Intelligence & Data Science',
    description: 'Deep neural models, statistical inference, data engineering pipelines, and NLP systems.',
    hodName: 'Dr. Vikramaditya Roy',
    studentCount: 320,
    facultyCount: 18,
    coursesCount: 22,
    avgAttendance: 88.2,
  },
  {
    id: 'dept-ece',
    code: 'ECE',
    name: 'Electronics & Communication Engineering',
    description: 'VLSI architectures, embedded robotics, wireless communications, and signal synthesis.',
    hodName: 'Dr. Meenakshi Sundaram',
    studentCount: 410,
    facultyCount: 24,
    coursesCount: 28,
    avgAttendance: 82.4,
  },
  {
    id: 'dept-mech',
    code: 'MECH',
    name: 'Mechanical & Automation Engineering',
    description: 'Thermodynamics, additive manufacturing, CAD simulation, and mechatronic control.',
    hodName: 'Prof. Harish Bhat',
    studentCount: 360,
    facultyCount: 22,
    coursesCount: 26,
    avgAttendance: 81.1,
  },
];

export const INITIAL_CLASSES: AcademicClass[] = [
  {
    id: 'class-cse-3a',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    code: 'CSE-3A',
    name: 'B.Tech CSE Year 3 Section A',
    academicYear: '2025-2026',
    semester: 6,
    advisorId: 'user-tch-01',
    advisorName: 'Dr. Ramesh Kulkarni',
    studentCount: 64,
  },
  {
    id: 'class-cse-3b',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    code: 'CSE-3B',
    name: 'B.Tech CSE Year 3 Section B',
    academicYear: '2025-2026',
    semester: 6,
    advisorName: 'Dr. Kavita Joshi',
    studentCount: 62,
  },
  {
    id: 'class-aids-2a',
    departmentId: 'dept-aids',
    departmentCode: 'AI&DS',
    code: 'AIDS-2A',
    name: 'B.Tech AI&DS Year 2 Section A',
    academicYear: '2025-2026',
    semester: 4,
    advisorName: 'Prof. Anirudh Sen',
    studentCount: 58,
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs-001',
    code: 'CS301',
    title: 'Database Management Systems',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    credits: 4,
    semester: 6,
    syllabus: 'Relational Algebra, SQL Optimization, B+ Tree Indexing, ACID Concurrency Control, Recovery Protocols, NoSQL Architectures.',
    instructorId: 'user-tch-01',
    instructorName: 'Dr. Ramesh Kulkarni',
    schedule: 'Mon, Wed, Fri (09:00 - 10:00 AM)',
    room: 'Hall 302 (Turing Block)',
    category: 'Core',
    enrolledStudentsCount: 64,
    status: 'ACTIVE',
  },
  {
    id: 'crs-002',
    code: 'CS302',
    title: 'Machine Learning Fundamentals',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    credits: 4,
    semester: 6,
    syllabus: 'Supervised Learning, Loss Landscapes, Regularization, Neural Networks, Backpropagation, Unsupervised Clustering, Dimensionality Reduction.',
    instructorId: 'user-tch-01',
    instructorName: 'Dr. Ramesh Kulkarni',
    schedule: 'Tue, Thu (10:30 - 12:00 PM)',
    room: 'Lab 4 (Euler Wing)',
    category: 'Core',
    enrolledStudentsCount: 64,
    status: 'ACTIVE',
  },
  {
    id: 'crs-003',
    code: 'CS303',
    title: 'Advanced Data Structures & Algorithms',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    credits: 4,
    semester: 6,
    syllabus: 'Disjoint Sets, Red-Black Trees, Maximum Flow, Dynamic Programming Optimizations, Approximation Algorithms, NP-Completeness.',
    instructorName: 'Prof. Sneha Deshmukh',
    schedule: 'Mon, Wed (02:00 - 03:30 PM)',
    room: 'Hall 305 (Turing Block)',
    category: 'Core',
    enrolledStudentsCount: 64,
    status: 'ACTIVE',
  },
  {
    id: 'crs-004',
    code: 'CS304',
    title: 'Modern Web Engineering & Cloud Systems',
    departmentId: 'dept-cse',
    departmentCode: 'CSE',
    credits: 3,
    semester: 6,
    syllabus: 'HTTP/3 Protocols, Micro-frontends, Edge Runtimes, Distributed Caching, Containerization, Infrastructure as Code.',
    instructorName: 'Dr. Amit Patel',
    schedule: 'Fri (11:00 AM - 01:00 PM)',
    room: 'Lab 2 (Lovelace Wing)',
    category: 'Elective',
    enrolledStudentsCount: 52,
    status: 'ACTIVE',
  },
  {
    id: 'crs-005',
    code: 'EC201',
    title: 'Digital Signal Processing',
    departmentId: 'dept-ece',
    departmentCode: 'ECE',
    credits: 3,
    semester: 4,
    syllabus: 'DFT/FFT Architectures, IIR/FIR Filter Synthesis, Wavelet Transforms, Real-time Audio Filtering, DSP Microprocessors.',
    instructorName: 'Dr. Meenakshi Sundaram',
    schedule: 'Mon, Thu (09:00 - 10:30 AM)',
    room: 'Hall 108 (Shannon Block)',
    category: 'Core',
    enrolledStudentsCount: 60,
    status: 'ACTIVE',
  },
];

export const INITIAL_ATTENDANCE_SESSIONS: AttendanceSession[] = [
  {
    id: 'att-sess-001',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    courseId: 'crs-001',
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    teacherId: 'user-tch-01',
    teacherName: 'Dr. Ramesh Kulkarni',
    sessionDate: '2026-08-16',
    startTime: '09:00 AM',
    status: 'ACTIVE',
    latitude: 12.9716,
    longitude: 77.5946,
    allowedRadiusMeters: 50,
    rotationIntervalSeconds: 15,
    stats: {
      totalStudents: 64,
      present: 54,
      flagged: 2,
      notScanned: 7,
      excused: 1,
    },
  },
];

export const INITIAL_ATTENDANCE_SCANS: AttendanceScanRecord[] = [
  {
    id: 'scan-001',
    sessionId: 'att-sess-001',
    studentId: 'user-std-01',
    studentName: 'Aarav Sharma',
    studentRegistrationNumber: 'NEGU2023CS042',
    state: 'PRESENT',
    scanTimestamp: '2026-08-16T09:04:12Z',
    studentLatitude: 12.97162,
    studentLongitude: 77.59463,
    calculatedDistanceMeters: 4.2,
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    sessionDate: '2026-08-16',
  },
  {
    id: 'scan-002',
    sessionId: 'att-sess-001',
    studentId: 'user-std-02',
    studentName: 'Priya Iyer',
    studentRegistrationNumber: 'NEGU2023CS019',
    state: 'PRESENT',
    scanTimestamp: '2026-08-16T09:03:45Z',
    studentLatitude: 12.97158,
    studentLongitude: 77.59461,
    calculatedDistanceMeters: 3.1,
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    sessionDate: '2026-08-16',
  },
  {
    id: 'scan-003',
    sessionId: 'att-sess-001',
    studentId: 'user-std-03',
    studentName: 'Rohan Verma',
    studentRegistrationNumber: 'NEGU2023CS088',
    state: 'FLAGGED',
    scanTimestamp: '2026-08-16T09:06:21Z',
    studentLatitude: 12.9725,
    studentLongitude: 77.5955,
    calculatedDistanceMeters: 142.8,
    flagReason: 'Outside allowable classroom geofence (143m > 50m limit)',
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    sessionDate: '2026-08-16',
  },
  {
    id: 'scan-004',
    sessionId: 'att-sess-001',
    studentId: 'user-std-04',
    studentName: 'Ananya Reddy',
    studentRegistrationNumber: 'NEGU2023CS055',
    state: 'EXCUSED',
    scanTimestamp: '2026-08-16T09:00:00Z',
    resolutionNotes: 'Automatically excused: Approved Medical Leave for 2026-08-16.',
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    sessionDate: '2026-08-16',
  },
  {
    id: 'scan-005',
    sessionId: 'att-sess-001',
    studentId: 'user-std-05',
    studentName: 'Karthik Menon',
    studentRegistrationNumber: 'NEGU2023CS071',
    state: 'FLAGGED',
    scanTimestamp: '2026-08-16T09:08:10Z',
    studentLatitude: 12.9721,
    studentLongitude: 77.5951,
    calculatedDistanceMeters: 78.4,
    flagReason: 'Outside allowable classroom geofence (78m > 50m limit)',
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    sessionDate: '2026-08-16',
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg-001',
    courseId: 'crs-001',
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    teacherId: 'user-tch-01',
    teacherName: 'Dr. Ramesh Kulkarni',
    title: 'Assignment 3: B+ Tree Indexing & Concurrency Plan',
    description: 'Implement a balanced B+ tree node split and merge simulation with node order M=4. Write query execution comparison against hash indexing under high read load.',
    dueDate: '2026-08-20T23:59:00Z',
    maxMarks: 100,
    createdAt: '2026-08-10T10:00:00Z',
    totalSubmissions: 48,
    gradedCount: 32,
  },
  {
    id: 'asg-002',
    courseId: 'crs-002',
    courseCode: 'CS302',
    courseTitle: 'Machine Learning Fundamentals',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    teacherId: 'user-tch-01',
    teacherName: 'Dr. Ramesh Kulkarni',
    title: 'Assignment 2: Backpropagation Engine from Scratch',
    description: 'Construct a 3-layer neural network using NumPy matrix operations without autograd frameworks. Implement Adam optimizer and plot loss curves.',
    dueDate: '2026-08-24T23:59:00Z',
    maxMarks: 50,
    createdAt: '2026-08-12T14:00:00Z',
    totalSubmissions: 41,
    gradedCount: 20,
  },
  {
    id: 'asg-003',
    courseId: 'crs-003',
    courseCode: 'CS303',
    courseTitle: 'Advanced Data Structures',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    teacherName: 'Prof. Sneha Deshmukh',
    teacherId: 'user-hod-01',
    title: 'Assignment 4: Dinic Algorithm for Maximum Flow',
    description: 'Design and benchmark Dinic maximum network flow against Edmonds-Karp on dense bipartite graph benchmark sets.',
    dueDate: '2026-08-28T23:59:00Z',
    maxMarks: 100,
    createdAt: '2026-08-14T09:30:00Z',
    totalSubmissions: 25,
    gradedCount: 0,
  },
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001',
    assignmentId: 'asg-001',
    assignmentTitle: 'Assignment 3: B+ Tree Indexing & Concurrency Plan',
    courseCode: 'CS301',
    studentId: 'user-std-01',
    studentName: 'Aarav Sharma',
    registrationNumber: 'NEGU2023CS042',
    content: 'Implemented B+ Tree split with O(log N) lookup guarantees and verified concurrent read locks using 2-Phase Locking protocol simulation.',
    submittedAt: '2026-08-15T18:22:00Z',
    status: 'GRADED',
    marksAwarded: 94,
    maxMarks: 100,
    teacherFeedback: 'Excellent implementation of node balancing. Comprehensive edge case proofs.',
    aiDraftFeedback: 'Solid implementation of B+ Tree split logic. Key strengths: robust pointer tracking and clean algorithmic proofs.',
    aiStrengths: ['Clean node split logic', 'Formal asymptotic proofs included'],
    aiWeaknesses: ['Slightly high memory overhead on bulk deletions'],
    aiSuggestions: ['Introduce delayed node merging to reduce tree churn'],
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-001',
    courseId: 'crs-001',
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    title: 'Mid-Semester Assessment Exam',
    examDate: '2026-08-05',
    maxMarks: 100,
    weightagePercent: 30,
  },
  {
    id: 'exam-002',
    courseId: 'crs-002',
    courseCode: 'CS302',
    courseTitle: 'Machine Learning Fundamentals',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    title: 'Mid-Semester Theory & Practical',
    examDate: '2026-08-07',
    maxMarks: 100,
    weightagePercent: 30,
  },
];

export const INITIAL_GRADES: GradeRecord[] = [
  {
    id: 'grd-001',
    examId: 'exam-001',
    examTitle: 'Mid-Semester Assessment Exam',
    courseCode: 'CS301',
    courseTitle: 'Database Management Systems',
    studentId: 'user-std-01',
    studentName: 'Aarav Sharma',
    registrationNumber: 'NEGU2023CS042',
    marksObtained: 89,
    maxMarks: 100,
    percentage: 89,
    letterGrade: 'A',
    remarks: 'Strong conceptual grasp of relational schema normalization.',
    gradedAt: '2026-08-08T12:00:00Z',
  },
  {
    id: 'grd-002',
    examId: 'exam-002',
    examTitle: 'Mid-Semester Theory & Practical',
    courseCode: 'CS302',
    courseTitle: 'Machine Learning Fundamentals',
    studentId: 'user-std-01',
    studentName: 'Aarav Sharma',
    registrationNumber: 'NEGU2023CS042',
    marksObtained: 92,
    maxMarks: 100,
    percentage: 92,
    letterGrade: 'A+',
    remarks: 'Flawless matrix formulation of backpropagation.',
    gradedAt: '2026-08-10T14:30:00Z',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'leave-001',
    studentId: 'user-std-04',
    studentName: 'Ananya Reddy',
    registrationNumber: 'NEGU2023CS055',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    fromDate: '2026-08-16',
    toDate: '2026-08-17',
    reason: 'Attending IEEE Student Technical Paper Presentation as primary author with institutional grant.',
    status: 'APPROVED',
    reviewedBy: 'user-tch-01',
    reviewerName: 'Dr. Ramesh Kulkarni',
    reviewedAt: '2026-08-14T11:00:00Z',
    reviewerNotes: 'Approved. Eligible attendance sessions marked as EXCUSED.',
    createdAt: '2026-08-13T16:00:00Z',
  },
  {
    id: 'leave-002',
    studentId: 'user-std-01',
    studentName: 'Aarav Sharma',
    registrationNumber: 'NEGU2023CS042',
    classId: 'class-cse-3a',
    classCode: 'CSE-3A',
    fromDate: '2026-08-25',
    toDate: '2026-08-26',
    reason: 'Smart India Hackathon Zonal Round representation representing University team.',
    status: 'PENDING',
    createdAt: '2026-08-15T09:15:00Z',
  },
];

export const INITIAL_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ai-001',
    studentId: 'user-std-01',
    studentName: 'Aarav Sharma',
    classId: 'class-cse-3a',
    insightType: 'STUDENT_RISK',
    riskLevel: 'LOW',
    title: 'Consistent Academic Momentum',
    summary: 'Attendance is sustained at 86.4% across all registered subjects. Assignment completion velocity is in the top 10% of CSE-3A with a 3.82 current GPA.',
    riskFactors: [
      { factor: 'Overall Attendance', metric: '86.4%', status: 'positive' },
      { factor: 'Average Midterm Score', metric: '90.5%', status: 'positive' },
      { factor: 'Pending Assignments', metric: '1 due soon', status: 'positive' },
    ],
    recommendations: [
      'Target CS303 Advanced Data Structures graph network flow algorithms for the upcoming assessment.',
      'Complete Assignment 2 for Machine Learning ahead of the weekend hackathon commitment.',
      'Maintain continuous attendance to lock in full internal assessment credits.',
    ],
    studyBlocks: [
      { day: 'Monday', subject: 'CS301 Database Systems', durationMinutes: 60, focusTopic: 'B+ Tree Concurrency & Index Merging', completed: true },
      { day: 'Tuesday', subject: 'CS302 Machine Learning', durationMinutes: 75, focusTopic: 'Adam Optimization Vectorized Matrix Math', completed: true },
      { day: 'Wednesday', subject: 'CS303 Advanced Algorithms', durationMinutes: 90, focusTopic: 'Dinic Max-Flow Graph Cut Reductions', completed: false },
      { day: 'Thursday', subject: 'CS304 Web Systems', durationMinutes: 60, focusTopic: 'Distributed Edge Caching Protocols', completed: false },
      { day: 'Friday', subject: 'Revision & Lab Practice', durationMinutes: 90, focusTopic: 'Mock Exam Problem Solving', completed: false },
    ],
    confidenceScore: 0.94,
    createdAt: '2026-08-16T06:00:00Z',
  },
  {
    id: 'ai-002',
    departmentId: 'dept-cse',
    insightType: 'DEPARTMENT_SUMMARY',
    riskLevel: 'LOW',
    title: 'Department Performance & Attendance Pulse',
    summary: 'Computer Science Department attendance averaged 85.6% this cycle (+2.4% over previous month). 4 students flagged for proactive faculty mentorship.',
    riskFactors: [
      { factor: 'Department Avg Attendance', metric: '85.6%', status: 'positive' },
      { factor: 'At-Risk Student Ratio', metric: '4 of 480 (0.8%)', status: 'positive' },
      { factor: 'Unresolved Geofence Flags', metric: '2 active today', status: 'warning' },
    ],
    recommendations: [
      'Conduct advisor review for 2 flagged geofence attendance records in CS301.',
      'Schedule tutorial remedial for CS303 Network Flow algorithms before unit test 2.',
    ],
    confidenceScore: 0.96,
    createdAt: '2026-08-16T07:30:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-001',
    userId: 'user-std-01',
    title: 'Attendance Verified',
    message: 'Your attendance for CS301 Database Systems was successfully marked PRESENT (verified within classroom boundary).',
    type: 'attendance_flag',
    isRead: false,
    createdAt: '2026-08-16T09:04:15Z',
  },
  {
    id: 'notif-002',
    userId: 'user-std-01',
    title: 'New AI Study Recommendation',
    message: 'Adaptive study routine for CS303 Advanced Data Structures updated based on recent assignment feedback.',
    type: 'ai_insight',
    isRead: false,
    createdAt: '2026-08-16T06:00:00Z',
  },
  {
    id: 'notif-003',
    userId: 'user-tch-01',
    title: '2 Students Flagged in Live Session',
    message: 'Rohan Verma and Karthik Menon were flagged outside the 50m classroom boundary for CS301.',
    type: 'attendance_flag',
    isRead: false,
    createdAt: '2026-08-16T09:08:15Z',
  },
];
